### ISSUE TITLE
ZeroDivisionError in 'fastp' MultiQC module for dataset with 0 reads

### ISSUE THREAD

**Issue by tbukur** [ewels/MultiQC#1466]
### Description of bug

The 'fastp' MultiQC module broke while running many samples. As it turned out, one of the samples had zero reads.

### MultiQC Error log

```console
============================================================
Module fastp raised an exception: Traceback (most recent call last):
  File "/code/Anaconda/3/2020.07/lib/python3.8/site-packages/multiqc/multiqc.py", line 594, in run
    output = mod()
  File "/code/Anaconda/3/2020.07/lib/python3.8/site-packages/multiqc/modules/fastp/fastp.py", line 47, in __init__
    self.parse_fastp_log(f)
  File "/code/Anaconda/3/2020.07/lib/python3.8/site-packages/multiqc/modules/fastp/fastp.py", line 201, in parse_fastp_log
    self.fastp_data[s_name]["after_filtering_total_reads"]
ZeroDivisionError: float division by zero
============================================================
```

### File that triggers the error

[SRR12380136.fastp_stats.json.txt](https://github.com/ewels/MultiQC/files/6726407/SRR12380136.fastp_stats.json.txt)

### Command used to run MultiQC

multiqc -l fastp_json_files.txt -c .my_multiqc.yaml

### MultiQC Version

multiqc, version 1.10.1

### Operating System

CentOS Linux 7

### Python Version

Python 3.8.3

**Comment by ErikDanielsson** [comment]
This is solved as of #1451, which is included in the current development version: v1.11.dev.

**Comment by bjohnnyd** [comment]
@ErikDanielsson  and @ewels  I am hitting this same error in fastp module in samples with zero reads using the current 1.11 release which includes the #1451.

I am using version `multiqc-1.11-pyhdfd78af_0`  and the error still occurs but I can see that this `ZeroDivisionError` catch form #1451 is not covering all the cases in `fastp.py` module.

The `ZeroDivsionError` should also be caught here:

https://github.com/ewels/MultiQC/blob/d6d1332a947670274ad489dac8ba96da0a848e92/multiqc/modules/fastp/fastp.py#L228-L235

and I can do a quick PR if needed.
