### ISSUE TITLE
`multiqc_general_stats.txt` is empty

### ISSUE THREAD

**Issue by g-pacheco** [ewels/MultiQC#1588]
### Description of bug

Hello, 

I have been using version **v1.12.dev0** and I have noticed that the files `multiqc_general_stats.txt` is written but it is empty. Was this function disabled on purpose? It is a very useful file, so I am hoping that this is a bug ^^  

Thanks a lot, George.

![Screenshot (268)](https://user-images.githubusercontent.com/37849281/141846853-5ab5ba73-4e06-48cf-bb66-86eb3b9aaf92.png)

**Comment by ewels** [comment]
huh, oops! Yes that's very definitely a bug.. Well spotted, thanks!

**Comment by ewels** [comment]
It looks like the file is created by the regular `table.plot()` function, here: https://github.com/ewels/MultiQC/blob/5ab527b74721e44c9070032855e5019651d0fbc3/multiqc/multiqc.py#L832-L838

So if the table is showing properly in the report, and this function is working for other modules / tables (is it..?) I have no idea why the General Stats file would suddenly be empty... 🤔

**Comment by g-pacheco** [comment]
Hej.

It also seems that the written files changed quite a bit. Maybe there is a connection with this change?

Best regards, George.

![NEW](https://user-images.githubusercontent.com/37849281/142849143-1971f018-f791-4980-82ba-5326812c1158.png)
![OLD](https://user-images.githubusercontent.com/37849281/142849146-dd511c5c-eb5c-42fa-8d60-90c705c39c0f.png)

**Comment by g-pacheco** [comment]
Hello, 

May I ask if there has been any development here?

Best regards, George.

**Comment by g-pacheco** [comment]
Hej @ewels --

Any news here?

**Comment by ewels** [comment]
Not yet. I've had a speed look, just to see if I could spot anything obvious. But I haven't had a chance to properly dig into it yet.

If you're able to find the culprit then please submit a pull-request with a fix 👍

**Comment by ewels** [comment]
Fixed by @MatthiasZepper in #1609 after a fairly in-depth investigation!

**Comment by g-pacheco** [comment]
Hej, 

Thanks so much for fixing this. I am sorry, but I am still learning about the different versions of a repository on _GitHub_. I tried to update _MultiQC_ like this:

```
source activate WHOLE_PATH_TO_MULTIQC_CONDA_ENVIRONMENT
conda update multiqc
conda deactivate
```

Then the file was still not created. Then I tried to update it like this instead:

```
source activate WHOLE_PATH_TO_MULTIQC_CONDA_ENVIRONMENT
pip uninstall multiqc
pip install git+git://github.com/ewels/MultiQC@master
conda deactivate
```

Then the file was created indeed :). However, the `mosdepth_mqc-generalstats-mosdepth-mean_coverage` column that had been implemented in [#1566](https://github.com/ewels/MultiQC/issues/1566) is missing. Have I installed the wrong version? If so, could you please tell me which version I should install that would have both modifications implemented?

I am sorry for the silly question. 

Best regards, George.

**Comment by ewels** [comment]
Looks good! Though I don't think you need to deactivate the conda environment after you installed MultiQC into it?

Issue #1566 is still open, there are pull requests created to solve it but they have not yet been merged. So it's not implemented yet.

**Comment by g-pacheco** [comment]
Thanks for your quick reply, @ewels!
And my bad -- I do not know how I did not notice that [#1566 (https://github.com/ewels/MultiQC/issues/1566) is actually still open -- I hope it will be implemented soon ^^
