### ISSUE TITLE
Could not parse sample name from fastp command

### ISSUE THREAD

**Issue by mptrsen** [ewels/MultiQC#2184]
### Description of bug

Error message: see title.

MultiQC doesn't find any analysis results in Fastp reports.

Running MultiQC 1.17.

I am a bit confused because:

a) the error message is lacking a "the" from the message in the [actual module code](https://github.com/ewels/MultiQC/blob/29e396b67ac3ce63f13252991e940170495b2de8/multiqc/modules/fastp/fastp.py#L190)
b) the [pattern](https://github.com/ewels/MultiQC/blob/29e396b67ac3ce63f13252991e940170495b2de8/multiqc/modules/fastp/fastp.py#L184) should be picking up the sample name from the `--in1` parameter
b) the Fastp module doesn't fall back to using the file name instead

Using `--fullnames` or `--fn_as_s_name` makes no difference.

### File that triggers the error

[JE93Mon_EKDN230037529-1A_HHN5VDSX7_L2.fastp.json](https://github.com/ewels/MultiQC/files/13392237/JE93Mon_EKDN230037529-1A_HHN5VDSX7_L2.fastp.json)

### MultiQC Error log

```console
$ multiqc --outdir mqc --filename mqc.html JE93Mon_EKDN230037529-1A_HHN5VDSX7_L2.fastp.json 

  /// MultiQC 🔍 | v1.17 (60b405b)

|           multiqc | Not cleaning sample names
|           multiqc | Search path : /shared/malte/projects/trichodes-qc/results/02_fastp/report/JE93Mon_EKDN230037529-1A_HHN5VDSX7_L2.fastp.json
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1  
|             fastp | Could not parse sample name from fastp command: JE93Mon_EKDN230037529-1A_HHN5VDSX7_L2.fastp.json
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete

```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Hi @mptrsen - sorry about this bug, and thanks for reporting the issue, and including the reproducible example!

It is fixed in the current (unreleased) codebase, and we are actually working on releasing 1.18 today. It will be out within an hour, hopefully :)

**Comment by mptrsen** [comment]
Awesome, thanks for the speedy response!

**Comment by vladsavelyev** [comment]
@mptrsen 1.18 is released! You can update with:

```sh
pip install multiqc==1.18
```

**Comment by ailtonpcf** [comment]
I'm using multiqc through singularity with docker://ewels/multiqc:v1.18 and multiqc still don't recognize fastp outputs :/ fastqc dirs are detected, while 12-trmmed-single and 12-trmmed-merged are ignored :/

`[Tue Nov 21 17:29:48 2023]
rule multiqc_marine:
    input: cache/09-generalists-in-marine/fastqc-raw-paired/SRR5176043_1_fastqc.html, cache/09-generalists-in-marine/fastqc-raw-paired/SRR5176043_2_fastqc.html, cache/09-generalists-in-marine/fastqc-raw-paired/SRR5176044_1_fastqc.html, cache/09-generalists-in-marine/fastqc-raw-paired/SRR5176044_2_fastqc.html, cache/09-generalists-in-marine/fastqc-raw-single/SRR8487001_fastqc.html, cache/09-generalists-in-marine/12-trmmed-merged/SRR5176043.html, cache/09-generalists-in-marine/12-trmmed-merged/SRR5176044.html, cache/09-generalists-in-marine/12-trmmed-single/SRR8487001.html
    output: cache/09-generalists-in-marine/multiqc-report
    jobid: 0
    reason: Missing output files: cache/09-generalists-in-marine/multiqc-report
    resources: mem_mb=10000, disk_mb=0, tmpdir=/scratch/qi47rin, partition=standard, qos=normal, time=3-00:00:00


        multiqc             --force             --dirs             --dirs-depth 1             --outdir cache/09-generalists-in-marine/multiqc-report cache/09-generalists-in-marine/fastqc-raw-paired cache/09-generalists-in-marine/fastqc-raw-single cache/09-generalists-in-marine/12-trmmed-single cache/09-generalists-in-marine/12-trmmed-merged
        
Activating singularity image /home/qi47rin/proj/04-global-microbiome/cache/00-singularity/f2cb2a5dc57fa4afb3d70d3136d20467.simg

  /// MultiQC 🔍 | v1.18

|           multiqc | Prepending directory to sample names
|           multiqc | Search path : /home/qi47rin/proj/04-global-microbiome/cache/09-generalists-in-marine/fastqc-raw-paired
|           multiqc | Search path : /home/qi47rin/proj/04-global-microbiome/cache/09-generalists-in-marine/fastqc-raw-single
|           multiqc | Search path : /home/qi47rin/proj/04-global-microbiome/cache/09-generalists-in-marine/12-trmmed-single
|           multiqc | Search path : /home/qi47rin/proj/04-global-microbiome/cache/09-generalists-in-marine/12-trmmed-merged
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 19/19  
|            fastqc | Found 5 reports
|           multiqc | Report      : cache/09-generalists-in-marine/multiqc-report/multiqc_report.html
|           multiqc | Data        : cache/09-generalists-in-marine/multiqc-report/multiqc_data
|           multiqc | MultiQC complete
[Tue Nov 21 17:29:53 2023]
Finished job 0.
1 of 1 steps (100%) done`

**Comment by mptrsen** [comment]
MultiQC uses the JSON report files from Fastp, not the HTML files.

**Comment by ailtonpcf** [comment]
I agree, but still, multiqc is not parsing/finding json files from fastp. I've tried with conda(multiqc 1.18) and singularity (multiqc 1.18, 1.17)

**Comment by mptrsen** [comment]
The Snakemake rule you showed above uses the HTML files as input, not the JSON files. Try adjusting the input.

**Comment by mptrsen** [comment]
Because you are still using the HTML files as input.

Change `{ID}.html` to `{ID}.json` and make sure that the Fastp rule(s) produce(s) the JSON files.
