### ISSUE TITLE
No handlers could be found for logger "multiqc"

### ISSUE THREAD

**Issue by royfrancis** [ewels/MultiQC#272]
Hi,
I have tried MultiQC with FastQC output and it works. Now I am trying with Skewer log files and I can't get it to work.

Running `multiqc ./path/` returns 'No results found'. So looking into the config, I found
```
skewer:
    contents: COMMAND LINE:	 skewer
```
but my log file has a full path `/path/path/skewer`. So, I created a multiqc_config.yaml in the working directory and included :

```
skewer:
    contents: COMMAND LINE:	 /path/path/skewer
```

and ran `multiqc ./path/` I get this error: `No handlers could be found for logger "multiqc"`

My log files are named 
```
a02-trimmed.log
k12-trimmed.log
m13-trimmed.log
...
```

I have tried many variations

```
sp:
        skewer:
                contents: COMMAND LINE:	 /path/path/skewer
                fn: trimmed.log

```
```
sp:
        skewer:
                fn: trimmed.log

```
```
sp:
        skewer:
                contents: null
                fn: trimmed.log

```
Also tried `multiqc -m skewer ./path/`.

They all result in the same error.

**Comment by ewels** [comment]
Hi @royfrancis,

You've been unlucky here and come into two different bugs in one go. You're completely correct that the skewer pattern match won't work for you with the `/path/path/skewer` - I need to change this to something else that will always match.

The second problem will have arrived when you started playing with the YAML file. My guess is that there's some problem with the syntax of your YAML which is triggering an error when MultiQC tries to parse it. This is caught and an error displayed, however it was done before the logging was initialised which gives you the different (and totally unhelpful) error message `No handlers could be found..`.

Hopefully you're using MultiQC v0.7, as I came across exactly the same bug last week and fixed it. So if you get a copy of the latest v0.8dev, you should get a more instructive error message saying something that there's a problem in the YAML.

My guess is that you were pretty much spot on with your first go, though it's more likely to work in single quotes:
```yaml
sp:
    skewer:
        contents: 'COMMAND LINE:  /path/path/skewer'
```

However, this is something that I should fix anyway. So I'll probably change it to `contents: 'maximum error ratio allowed (-r):'` which should work for everybody. I'll post here when I've done that, then you can remove the custom matching completely and update to v0.8dev and hopefully everything will just work for you.

Apologies for any frustration caused!

Phil

**Comment by ewels** [comment]
Hi @royfrancis,

I've just updated one of my test files to have the same `/path/to/skewer` format, then updated MultiQC to still find that log file (and others). I've tested it at my end and it seems to work ok.

If you could update to v0.8dev and give it a test, that would be great! Feel free to reopen this issue if you're still having problems.

Cheers,

Phil

**Comment by royfrancis** [comment]
Thanks for the quick response. Umm.. I updated to the new version and it still does not work for me.

```
[bla@bla bla]$ multiqc -m skewer ./trimmed-log
[INFO   ]         multiqc : This is MultiQC v0.8.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './trimmed-log'
[INFO   ]         multiqc : Only using modules skewer
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

[bla@bla bla]$ multiqc ./trimmed-log
[INFO   ]         multiqc : This is MultiQC v0.8.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './trimmed-log'
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

The dir path I have provided contains only skewer log files to avoid potential confusion with other file types. I am attaching two sample log files. (Renamed ending .log to .txt because github was fussy about it).


[a01-trimmed.txt](https://github.com/ewels/MultiQC/files/386577/a01-trimmed.txt)
[a02-trimmed.txt](https://github.com/ewels/MultiQC/files/386576/a02-trimmed.txt)

**Comment by ewels** [comment]
Hi @royfrancis,

After briefly panicking that the format of Skewer logs had changed in a recent update, I think I found the cause of the error. It was simply that your input files had the extension `.fq.gz` and the module was only written to handle `.fastq` extensions. I updated the regex and I think it should work now.

Let me know if you have any problems with this version..

Cheers,

Phil

**Comment by ewels** [comment]
..just updated again - I figured that there's no reason to restrict to any file extension with this regex. So should now work with whatever file extension you throw at skewer.

**Comment by royfrancis** [comment]
I reinstalled like so:
`pip install git+https://github.com/ewels/MultiQC`

and the version number is the old version `MultiQC v0.8.dev0`. Not sure if it is actually the old version or it's the new version and the number was just not changed. Either way, it still does not work with skewer log files.

**Comment by ewels** [comment]
Hmm, if it was already installed then it's possible that you might need to use `--upgrade` as the version number hasn't changed.

I just tested it with a fresh install and the log files that you sent through and it seemed to work fine:

```bash
conda create --name testing python pip
source activate testing
pip install git+https://github.com/ewels/MultiQC
multiqc -f MultiQC_TestData -m skewer
```
```
[INFO   ]         multiqc : This is MultiQC v0.8.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'MultiQC_TestData/'
[INFO   ]         multiqc : Only using modules skewer
[INFO   ]          skewer : Found 5 reports
[WARNING]         multiqc : Deleting    : multiqc_report.html   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc_report.html
[WARNING]         multiqc : Deleting    : multiqc_data   (-f was specified)
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

Apparently you can also install a specific commit using pip:
```
pip install git+git://github.com/ewels/MultiQC.git@02a1d66c786c60cdb28672cb7815bc4a56a2eed6
```

**Comment by royfrancis** [comment]
The specific commit worked. The version is still `v0.8.dev0`, but anyway it works now.

```bash
[bla@bla bla]$ multiqc ./trimmed-log/
[INFO   ]         multiqc : This is MultiQC v0.8.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './trimmed-log/'
[INFO   ]          skewer : Found 384 reports
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```
Thanks for all the help :-)

**Comment by ewels** [comment]
Brilliant! Yes pip tends to be quite lazy with installing new stuff if the version number doesn't change. Great that you got it to work, thanks for reporting the problems..

Phil
